overwrite: true
schema:
  - 'http://localhost:3000/graphql'
documents:
  - 'src/**/*.query.graphql'
  - 'src/**/*.mutation.graphql'
generates:
  ./src/lib/graphql/generated/resolvers.ts:
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
    config:
      useTypeImports: true
      immutableTypes: true
      contextType: $lib/graphql/schema#Context
      mappers:
        Ship: $lib/graphql/services/ships/data#MyShipInfo
  ./graphql.schema.json:
    plugins:
      - 'introspection'
  ./src/lib/graphql/generated/operations.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
    config:
      useTypeImports: true
  ./src/lib/graphql/generated/urqlIntrospection.ts:
    plugins:
      - urql-introspection
    config:
      useTypeImports: true

hooks:
  afterOneFileWrite:
    - prettier --write
